### ISSUE TITLE
Refresh app list when new app is installed

### ISSUE THREAD

**Issue by schrnz** [Project-ARTist/ArtistGui#1]
When we install an application (e.g., via adb) while the view displaying installed apps is already in the foreground, the new app does not show up and we need to close the view and reopen it to see the change.

It would be nice to have this view auto-refresh as soon as an application is installed.

**Comment by sweisgerber-dev** [comment]
This feature already works. Verified in 02b53bd0204240c4fd416a6b2a39d56be044753d

**Comment by schrnz** [comment]
Just tested in 7.1.1 (Pixel) and 7 (Pixel C) @ 02b53bd,
the app list is NOT refreshed and hence the newly installed app does not appear. 
We should dig into this to find the reason for the diverging test results.

**Comment by sweisgerber-dev** [comment]
Hints for a proper implementation: Intent to listen to: com.android.vending.INSTALL_REFERRER
More Information: https://developers.google.com/android/reference/com/google/android/gms/tagmanager/InstallReferrerReceiver
(Probably does not work for `adb install <APP>`)

**Comment by sweisgerber-dev** [comment]
Already checked my application for any useful logs, but nearly none are generated during the installation and none indicate anything related to it. -.-

**Comment by schrnz** [comment]
```
IntentFilter intentFilter = new IntentFilter();
intentFilter.addAction(Intent.ACTION_PACKAGE_ADDED);
intentFilter.addAction(Intent.ACTION_PACKAGE_INSTALL);
intentFilter.addDataScheme("package");
registerReceiver(ctx intentFilter);
```
should do the trick. Registering and unregistering dynamically.

**Comment by sweisgerber-dev** [comment]
Added a few more or less interesting hooks

```
ACTION_INSTALL_PACKAGE
ACTION_MY_PACKAGE_REPLACED
ACTION_PACKAGES_SUSPENDED
ACTION_PACKAGES_UNSUSPENDED
ACTION_PACKAGE_ADDED
ACTION_PACKAGE_CHANGED
ACTION_PACKAGE_DATA_CLEARED
ACTION_PACKAGE_FIRST_LAUNCH
ACTION_PACKAGE_FULLY_REMOVED
ACTION_PACKAGE_INSTALL
ACTION_PACKAGE_NEEDS_VERIFICATION
ACTION_PACKAGE_REMOVED
ACTION_PACKAGE_REPLACED
ACTION_PACKAGE_RESTARTED
ACTION_PACKAGE_VERIFIED
ACTION_UNINSTALL_PACKAGE
```
[<https://developer.android.com/reference/android/content/Intent.html>]
