### ISSUE TITLE
DexMerger: Replace codelib detection heuristic

### ISSUE THREAD

**Issue by schrnz** [Project-ARTist/ArtistGui#6]
DexMerger's current implementation uses a hacky heuristic to detect which dex file is the codelib:
During development, our codelibs were always pretty small, hence the check [here](https://github.com/Project-ARTist/ArtistGui/blob/master/dx/src/main/java/com2/android/dx/merge/DexMerger.java#L675) tests for the method ID count.
Obviously, this does not work for bigger codelibs and hence we need to replace it.

We can hardly detect codelibs in a generic way since, as of now, they do not have a common format. 
Therefore, it might be easier to provide the codelib explicitly and store this information throughout the process.

**Comment by sweisgerber-dev** [comment]
Fixed in #75a42385b2a6d16b97e84f7832f8503ffdcd172e https://github.com/Project-ARTist/dexterous/tree/fix_codelib_detection

No Automatic detection, but automatic detection could be possible if all CodeLibs implement a specific interface.

**Comment by sweisgerber-dev** [comment]
Please also test with your use-case @schrnz
