### ISSUE TITLE
Travis CI doesn't start emulator, highest supported API level is 25

### ISSUE THREAD

**Issue by parthipanramesh** [Project-ARTist/ArtistGui#81]
In Travis we run ./gradlew build connectedCheck [(line 43)](https://github.com/Project-ARTist/ArtistGui/blob/dbff2ff04b282652e381bf90c345c1db9d3d7b6d/.travis.yml#L43). "build" builds the app and runs the unit tests. "connectedCheck" executes the instrumentation tests on an Android device (physical) or an emulator. However we don't create/start an emulator.

Another problem is that Travis CIs highest supported API level is 25 (ArtistGui supports higher versions).
The main problem is that Travis updates/installs its components using the deprecated android binary (in the sdk). I updated the android-sdk cookbook and opened pull request (travis-ci/travis-cookbooks#992).

**Comment by schrnz** [comment]
So why is the command succeeding if the emu is not starting?

**Comment by parthipanramesh** [comment]
We don't have espresso tests (ui tests) yet.
