### ISSUE TITLE
How can i get dex2oat on android-23\android-24\android-26

### ISSUE THREAD

**Issue by lietdai** [Project-ARTist/ArtistGui#84]

**Comment by lietdai** [comment]
In the apk, i just can see `dex2oat` file in folder of "Assets\artist\android-25"
how about others ?

**Comment by schrnz** [comment]
Hi there, for time reasons we only published ready-made versions of ARTist/ArtistGui for API level 24 (Nougat) und 25 (Nougat 7.1) for the beta, you can download ArtistGui versions with the correct compiler already embedded [here](https://github.com/Project-ARTist/ArtistGui/releases). For 23 (Marshmallow) and 26 (Oreo), the art & ARTist repos are a bit behind, check Project-ARTist/art#17 and Project-ARTist/art#18 for progress. 

If you want to work with the source of ArtistGui, you can download ARTist versions [here](https://github.com/Project-ARTist/ARTist/releases). Those can literally be copy-pasted into the corresponding folder of ArtistGui. If you have more questions or want to discuss those things in more detail, we also have a [Gitter chat](https://gitter.im/project-artist/). It should work smoothly with your GitHub account.

Does this answer your question?

**Comment by lietdai** [comment]
Yes， Thanks a lot!
